### ISSUE TITLE
Asethetic:modal does not view as full when clicking any app in marketplaces

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/nilavu#1081] opened 2016-08-26 09:59 UTC
![screenshot from 2016-08-26 15-27-25](https://cloud.githubusercontent.com/assets/17096693/18001700/da85498e-6ba1-11e6-8f3d-f69ba706d400.png)

**Comment by vinomca-megam** [comment] 2016-09-02 07:40
@jaeko44  are you fix this?

**Comment by jaeko44** [comment] 2016-09-02 08:07
I think this is fixed now:

http://puu.sh/qXb22/dc73c1ae03.png

I made the height very short : 428px in chrome to check if it is going outside but it looks ok.

**Comment by vinomca-megam** [comment] 2016-09-02 10:53
Now i checked that still has same problem.Choose the App from marketplaces.we can't get the modal as full view.But when we launch the VM/App from the dashboard modal works good.

**Comment by jaeko44** [comment] 2016-09-02 11:01
Can you show me a screenshot of the issue I'm not able to reproduce it.

**Comment by vinomca-megam** [comment] 2016-09-02 11:04
yeah i will send

**Comment by vinomca-megam** [comment] 2016-09-02 11:04
![screenshot from 2016-09-02 13-09-12](https://cloud.githubusercontent.com/assets/17096693/18202013/21b10846-712b-11e6-9528-694dfa46fd75.png)

**Comment by vinomca-megam** [comment] 2016-09-02 11:05
i can't get the top view of the modal when i click App from marketplaces

**Comment by jaeko44** [comment] 2016-09-02 11:05
What is your screen width/height and what version of chrome is this.

**Comment by vinomca-megam** [comment] 2016-09-02 11:08
when i click create VM/App  from dashboard Modal look good
![screenshot from 2016-09-02 16-36-37](https://cloud.githubusercontent.com/assets/17096693/18202094/a020c0c2-712b-11e6-894d-18bddddb8f87.png)

**Comment by jaeko44** [comment] 2016-09-02 11:09
I tried to reproduce with no luck, tried on Chrome (latest version) & also IE Edge

https://drive.google.com/file/d/0B8SjLIoi686zblc1M3JHMkM2RWs/view?usp=sharing

Can you try in a different browser? Also can you ensure that you merged https://github.com/megamsys/nilavu/pull/1095 before trying.

**Comment by vinomca-megam** [comment] 2016-09-02 11:10
Version 52.0.2743.116 (64-bit)

**Comment by jaeko44** [comment] 2016-09-02 11:13
Also just tested in an old version of chrome:

http://puu.sh/qXhca/687c0f5691.png

**Comment by vinomca-megam** [comment] 2016-09-02 11:13
i merged your pull request and once i check in another browser let you know

**Comment by vinomca-megam** [comment] 2016-09-02 12:38
@jaeko44 
- Firefox `48.0`, has the same problem.
- Screen width X Height : 

![screenshot from 2016-09-02 18-14-59](https://cloud.githubusercontent.com/assets/17096693/18204266/72746c6a-7139-11e6-9c1f-10a17e1eda91.png)
- I have tested with #1095  merged.

### Steps to recreate the problem
- From marketplaces-  `Click Ubuntu OS`, Now I can see the full Modal view **correctly**.
- Then scroll the page up to `App`, Click  `C/C++` now,  the modal looks like below
  ![screenshot from 2016-09-02 18-05-16](https://cloud.githubusercontent.com/assets/17096693/18204033/1b5dda52-7138-11e6-8519-701c6eed1a2c.png)

**Comment by jaeko44** [comment] 2016-09-02 12:51
Hello,

I have been able to re-create this.

Clicking create VM Modal will work every time. 
Clicking create APP Modal @ home will work for me only when my screen is full height. However when I open console and it becomes shorter then it is broken: http://puu.sh/qXl5B/8cb5f8e20e.png

What is going on the back, what is the difference between VM & APP Modal? I am trying to fix it from CSS however no luck so far. Will let you know if I got a fix.

**Comment by jaeko44** [comment] 2016-09-02 13:27
Ok this also happens to Virtual Machines when the window height is short enough.

**Comment by vinomca-megam** [comment] 2016-09-02 13:28
Yes now i noticed

**Comment by indykish** [comment] 2016-09-05 01:55
cool. :+1:

**Comment by jaeko44** [comment] 2016-09-05 05:32
This is an issue with Discourse modals, this behaviour also happens to the password reset modal when the screen is too short.

We can fix this two ways: Try to debug the issue with the Discourse modals, or we can move to a different kind of modals that are already available in our code base such as bootstrap since bootstrap is already a requirement in our app.

@indykish

**Comment by indykish** [comment] 2016-09-05 07:47
@jaeko44  So as we discussed via skype,  you found out that `try.discourse.org` doesn't have this problem. You were going to compare `discourse modal` and our `modal` to see if it works.

```
they use this to spawn the modal
this._autoLogin('login', 'login-modal', () => this.controllerFor('login').resetForm());
_autoLogin(modal, modalClass, notAuto) {

they do two things to spawn the modal inside the autoLogin funct
'      showModal(modal);
      this.controllerFor('modal').set('modalClass', modalClass);'
showModal & this.controllfor 

Currently in Nilavu it is only
this.controllerfor

any reason you removed showModal() or should I try to add that back in?

Yes try it out.
```

**Comment by jaeko44** [comment] 2016-09-05 18:26
Figured out the issue with this, it's nothing to do with the modal and was caused by one of the child elements having '100vh' as their height property. 

Will close on next merge.

**Comment by jaeko44** [comment] 2016-09-05 18:38
Here is the css code that caused the bug. 

```
    .modal-body {
        &.full-height-modal {
            max-height: calc(100vh - 150px);
        }
    }
```

Just testing to make sure it's fixed and will push code.

**Closed as completed** 2016-09-06 06:51 UTC
