### ISSUE TITLE
Asethetic:when launch the app the page is not aligned and description details aren't shown there

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/nilavu#1082] opened 2016-08-26 10:20 UTC
![appcustompage](https://cloud.githubusercontent.com/assets/13765880/18002313/a7bd60e2-6ba4-11e6-99e3-f22168ca3b9d.png)

**Comment by indykish** [comment] 2016-08-29 05:55
1. The page needs to be make better Dup of #969 
2. The Top header is missing.

**Comment by jaeko44** [comment] 2016-09-04 20:17
This issue is partially fixed - 1. is fixed, 2 is duplicate of #1081.

Closing this issue.

**Closed as completed by jaeko44** 2016-09-04 20:17 UTC
Labels: kind/bug, priority/P2
